#!/usr/bin/env python3
"""Bake the expanded Stage 022 Malta/Gozo/Comino terrain grid.

The runway threshold remains Full Authority's local origin. The grid is deliberately
rectangular in local runway coordinates so the complete Maltese archipelago fits
without wasting most samples on Mediterranean water.
"""

from __future__ import annotations

import io
import json
import math
from pathlib import Path

import numpy as np
import requests
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT_INC = ROOT / "Simulation/Bridge/Stage022MaltaTerrain.inc"
OUT_META = ROOT / "Docs/Stage022MaltaTerrain.json"

ANCHOR_LAT = 35.8351666667
ANCHOR_LON = 14.5051666667
ANCHOR_HEADING_DEG = 312.0
ANCHOR_ELEVATION_M = 231.0 * 0.3048

MIN_X_M = -32_000.0
MAX_X_M = 32_000.0
MIN_Z_M = -16_000.0
MAX_Z_M = 48_000.0
SPACING_M = 125.0
RES_X = int(round((MAX_X_M - MIN_X_M) / SPACING_M)) + 1
RES_Z = int(round((MAX_Z_M - MIN_Z_M) / SPACING_M)) + 1
TERRARIUM_ZOOM = 11
SEA_LEVEL_LOCAL_M = -ANCHOR_ELEVATION_M
SEA_FLOOR_LOCAL_M = SEA_LEVEL_LOCAL_M - 24.0


def lonlat_to_tile(lon: float, lat: float, zoom: int) -> tuple[float, float]:
    n = 2.0 ** zoom
    x = (lon + 180.0) / 360.0 * n
    lat_rad = math.radians(max(min(lat, 85.05112878), -85.05112878))
    y = (1.0 - math.asinh(math.tan(lat_rad)) / math.pi) / 2.0 * n
    return x, y


def local_to_lonlat(x: float, z: float) -> tuple[float, float]:
    h = math.radians(ANCHOR_HEADING_DEG)
    east = x * math.cos(h) + z * math.sin(h)
    north = -x * math.sin(h) + z * math.cos(h)
    lat = ANCHOR_LAT + north / 110_540.0
    lon = ANCHOR_LON + east / (111_320.0 * math.cos(math.radians(ANCHOR_LAT)))
    return lon, lat


def fetch_terrarium_tile(tx: int, ty: int, cache: dict[tuple[int, int], np.ndarray]) -> np.ndarray:
    key = (tx, ty)
    if key in cache:
        return cache[key]
    url = f"https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{TERRARIUM_ZOOM}/{tx}/{ty}.png"
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    image = np.asarray(Image.open(io.BytesIO(response.content)).convert("RGB"), dtype=np.float32)
    elevation = image[:, :, 0] * 256.0 + image[:, :, 1] + image[:, :, 2] / 256.0 - 32768.0
    cache[key] = elevation
    print(f"Terrain tile {tx}/{ty}")
    return elevation


def sample_elevation(lon: float, lat: float, cache: dict[tuple[int, int], np.ndarray]) -> float:
    x, y = lonlat_to_tile(lon, lat, TERRARIUM_ZOOM)
    tx, ty = int(math.floor(x)), int(math.floor(y))
    fx, fy = (x - tx) * 256.0, (y - ty) * 256.0
    tile = fetch_terrarium_tile(tx, ty, cache)
    x0 = int(min(max(math.floor(fx), 0), 255))
    y0 = int(min(max(math.floor(fy), 0), 255))
    x1, y1 = min(x0 + 1, 255), min(y0 + 1, 255)
    ax, ay = fx - x0, fy - y0
    v0 = tile[y0, x0] * (1 - ax) + tile[y0, x1] * ax
    v1 = tile[y1, x0] * (1 - ax) + tile[y1, x1] * ax
    return float(v0 * (1 - ay) + v1 * ay)


def bake_terrain() -> np.ndarray:
    cache: dict[tuple[int, int], np.ndarray] = {}
    xs = np.linspace(MIN_X_M, MAX_X_M, RES_X, dtype=np.float64)
    zs = np.linspace(MIN_Z_M, MAX_Z_M, RES_Z, dtype=np.float64)
    dem = np.empty((RES_Z, RES_X), dtype=np.float32)

    print(f"Baking Stage 022 DEM {RES_X}x{RES_Z} at {SPACING_M:.0f} m spacing")
    for iz, z in enumerate(zs):
        for ix, x in enumerate(xs):
            lon, lat = local_to_lonlat(float(x), float(z))
            msl = sample_elevation(lon, lat, cache)
            local_height = SEA_FLOOR_LOCAL_M if msl <= 0.75 else msl - ANCHOR_ELEVATION_M
            dem[iz, ix] = local_height
        if iz % 32 == 0:
            print(f"Terrain row {iz + 1}/{RES_Z}")
    return dem


def write_include(dem: np.ndarray) -> None:
    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    values = np.clip(np.rint(dem * 10.0), -32768, 32767).astype(np.int16).ravel()
    with OUT_INC.open("w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/bake-stage022-terrain.py. Do not hand-edit.\n")
        handle.write(f"static constexpr int kFAStage022TerrainResolutionX = {RES_X};\n")
        handle.write(f"static constexpr int kFAStage022TerrainResolutionZ = {RES_Z};\n")
        handle.write(f"static constexpr double kFAStage022TerrainMinX = {MIN_X_M:.6f};\n")
        handle.write(f"static constexpr double kFAStage022TerrainMaxX = {MAX_X_M:.6f};\n")
        handle.write(f"static constexpr double kFAStage022TerrainMinZ = {MIN_Z_M:.6f};\n")
        handle.write(f"static constexpr double kFAStage022TerrainMaxZ = {MAX_Z_M:.6f};\n")
        handle.write(f"static constexpr double kFAStage022TerrainSpacingMeters = {SPACING_M:.9f};\n")
        handle.write(f"static constexpr double kFAStage022SeaLevelMeters = {SEA_LEVEL_LOCAL_M:.9f};\n")
        handle.write("static const int16_t kFAStage022TerrainDecimeters[] = {\n")
        for start in range(0, len(values), 24):
            chunk = values[start : start + 24]
            handle.write("    " + ", ".join(str(int(v)) for v in chunk) + ",\n")
        handle.write("};\n")


def main() -> None:
    dem = bake_terrain()
    write_include(dem)
    OUT_META.parent.mkdir(parents=True, exist_ok=True)
    metadata = {
        "stage": 22,
        "region": "Maltese archipelago",
        "anchor": {
            "name": "Malta International Airport runway 31 threshold",
            "latitude": ANCHOR_LAT,
            "longitude": ANCHOR_LON,
            "headingDegrees": ANCHOR_HEADING_DEG,
            "elevationMetersMSL": ANCHOR_ELEVATION_M,
        },
        "boundsMeters": {"minX": MIN_X_M, "maxX": MAX_X_M, "minZ": MIN_Z_M, "maxZ": MAX_Z_M},
        "terrainResolutionX": RES_X,
        "terrainResolutionZ": RES_Z,
        "terrainSpacingMeters": SPACING_M,
        "seaLevelLocalMeters": SEA_LEVEL_LOCAL_M,
        "source": f"Mapzen/AWS Terrarium zoom {TERRARIUM_ZOOM}",
    }
    OUT_META.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
